version: "3.8"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  app:
    build: .
    ports:
      - 4000:3000
    environment:
      APP_NAME: socialFeeds
      PORT: 3000
      MONGO_DB_URI: mongodb://mongo_db:27017/taskAssessment
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
